spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

Server:
  port: 8088
springdoc:
  swagger-ui:
    path: /swagger-ui.html
