spring:
  application:
    name: order-product-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
Server:
  port: 8088
springdoc:
  swagger-ui:
    path: /swagger-ui.html